/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archiwum.frontend;

import archiwum.backend.BazaDanych;
import archiwum.backend.Dokumenty;
import archiwum.backend.Pracownik;
import java.util.List;

/**
 *
 * @author annac
 */
public class EdytujDokumentFrame extends javax.swing.JFrame {

    /**
     * Creates new form EdytujDokumentFrame
     */
    public EdytujDokumentFrame() {
        initComponents();
        db = new BazaDanych();
        counterP = 0;
        counterD = 0;
        listaPracownikow = db.pracownicy();
        //1
        wyswietl(counterP, counterD);
        bPrPoprzedni.setEnabled(false);
        
    }
    private void wyswietl(int counterP, int counterD){	      
         this.p = listaPracownikow.get(counterP);
         tPracownik.setText(p.toString());
         this.listaDokumentow = db.dokumenty_idPracownika(p);
         if(listaDokumentow.size()==0){
             
            tRodzaj.setText("");
            tNazwa.setText("");
         }else{
         this.d = listaDokumentow.get(counterD);
         tRodzaj.setText(d.getRodzaj());
         tNazwa.setText(d.getNazwa());
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tPracownik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bPrPoprzedni = new javax.swing.JButton();
        bPrNastepny = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNazwa = new javax.swing.JTextField();
        tRodzaj = new javax.swing.JTextField();
        bDocPoprzedni = new javax.swing.JButton();
        bDocNastepny = new javax.swing.JButton();
        bModyfikuj = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Archiwum osobowe");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Edytuj dokument");

        tPracownik.setEditable(false);
        tPracownik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPracownikActionPerformed(evt);
            }
        });

        jLabel3.setText("Pracownik");

        bPrPoprzedni.setText("<");
        bPrPoprzedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrPoprzedniActionPerformed(evt);
            }
        });

        bPrNastepny.setText(">");
        bPrNastepny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrNastepnyActionPerformed(evt);
            }
        });

        jLabel4.setText("Nazwa");

        jLabel5.setText("Rodzaj");

        tNazwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNazwaActionPerformed(evt);
            }
        });

        tRodzaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRodzajActionPerformed(evt);
            }
        });

        bDocPoprzedni.setText("<");
        bDocPoprzedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDocPoprzedniActionPerformed(evt);
            }
        });

        bDocNastepny.setText(">");
        bDocNastepny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDocNastepnyActionPerformed(evt);
            }
        });

        bModyfikuj.setText("Modyfikuj");
        bModyfikuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModyfikujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tNazwa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(tPracownik, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tRodzaj))
                        .addGap(18, 18, 18)
                        .addComponent(bPrPoprzedni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bPrNastepny)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(bDocPoprzedni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bDocNastepny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bModyfikuj)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPracownik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(bPrPoprzedni)
                    .addComponent(bPrNastepny))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tRodzaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bDocPoprzedni)
                            .addComponent(bDocNastepny))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bModyfikuj)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPracownikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPracownikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPracownikActionPerformed

    private void tNazwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNazwaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNazwaActionPerformed

    private void tRodzajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRodzajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRodzajActionPerformed

    private void bPrPoprzedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrPoprzedniActionPerformed
        // TODO add your handling code here:
        if(counterP>0){
            counterP-=1;
            counterD=0;
            this.wyswietl(counterP,counterD);
            if(counterP==0) bPrPoprzedni.setEnabled(false);
            bPrNastepny.setEnabled(true);
        }
        
    }//GEN-LAST:event_bPrPoprzedniActionPerformed

    private void bPrNastepnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrNastepnyActionPerformed
        // TODO add your handling code here:
        if(counterP+1<listaPracownikow.size()){
            counterP+=1;
            counterD=0;
            this.wyswietl(counterP, counterD);
            if(counterP==listaPracownikow.size()-1) bPrNastepny.setEnabled(false);
            bPrPoprzedni.setEnabled(true);
        }
        
    }//GEN-LAST:event_bPrNastepnyActionPerformed

    private void bDocPoprzedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDocPoprzedniActionPerformed
        // TODO add your handling code here:
        if(counterD>0){
            counterD-=1;
            this.wyswietl(counterP,counterD);
            
        }
    }//GEN-LAST:event_bDocPoprzedniActionPerformed

    private void bDocNastepnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDocNastepnyActionPerformed
        // TODO add your handling code here:
        if(counterD+1<listaDokumentow.size()){
            counterD+=1;
            this.wyswietl(counterP, counterD);
            
        }
    }//GEN-LAST:event_bDocNastepnyActionPerformed

    private void bModyfikujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModyfikujActionPerformed
        // TODO add your handling code here:
        db.edytujDoc(d.getId(), tRodzaj.getText(), tNazwa.getText(),p);
        
    }//GEN-LAST:event_bModyfikujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdytujDokumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdytujDokumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdytujDokumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdytujDokumentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EdytujDokumentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDocNastepny;
    private javax.swing.JButton bDocPoprzedni;
    private javax.swing.JButton bModyfikuj;
    private javax.swing.JButton bPrNastepny;
    private javax.swing.JButton bPrPoprzedni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tNazwa;
    private javax.swing.JTextField tPracownik;
    private javax.swing.JTextField tRodzaj;
    // End of variables declaration//GEN-END:variables
    private BazaDanych db;
    private Pracownik p;
    private Dokumenty d;
    List<Pracownik> listaPracownikow;
    int counterP;
    int counterD;
    List<Dokumenty> listaDokumentow;
}
